(define (sqrt x)
  ;; x 不需要再子程序中显示的传递
  (define (good-enough? guess)
    (< (abs (- (square guess) x)) 0.001)
  )
  (define (average x y)
    (/ (+ x y) 2)
  )
  (define (improve guess)
    (average guess (/ x guess))
  )
  (define (sqrt-iter guess)
    (if (good-enough? guess)
        guess
        (sqrt-iter (improve guess)))
  )
  (sqrt-iter 1.0)
)

(sqrt 10)